TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sfi.Widgets': TRUE
    nodeTypes:
      groups:
        contentElements:
          position: 105
          label: 'Content Elements'
        contentBlocks:
          position: 110
          label: 'Content Blocks'
        contentWidgets:
          position: 120
          label: 'Content Widgets'
        system:
          position: end
          label: 'System'
