TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sfi.Shared': TRUE
    nodeTypes:
      groups:
        contentElements:
          position: 105
          label: 'Content Elements'
        contentBlocks:
          position: 110
          label: 'Content Blocks'
        structure:
          position: 115
          label: 'Structure'
        contentWidgets:
          position: 120
          label: 'Content Widgets'
        lists:
          position: 130
          label: 'Lists'
        system:
          position: end
          label: 'System'
  TypoScript:
    defaultContext:
      NodeTypeConfiguration: 'Sfi\Shared\TypoScript\Eel\Helper\NodeTypeConfigurationHelper'
